#!/bin/bash
echo "========================================="
echo "  m347 KN05 - Goncalo de Almeida"
echo "  Bind Mount Test Script - Version 2"
echo "  (Skript wurde auf dem Host geaendert!)"
echo "========================================="
echo ""
echo "Hostname: $(hostname)"
echo "Datum: $(date)"
echo "Verzeichnis: $(pwd)"
echo ""
echo "Neue Funktionalitaet in Version 2:"
echo "  - Zeigt Betriebssystem-Infos"
echo ""
echo "OS-Info: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '\"')"
echo "Kernel: $(uname -r)"
